apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-me-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: about-me-app
  template:
    metadata:
      labels:
        app: about-me-app
    spec:
      containers:
      - name: about-me-app
        image: manu/about-me-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: about-me-app-service
spec:
  selector:
    app: about-me-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
